### PR TITLE
Make SugarCrm match our component guidelines.

### PR DESCRIPTION
**Pull request by jhorbulyk**
All of the behavior in the component matches the behavior described by our component quality guidelines.  However, it still requires:
- [ ] A license
- [ ] A logo that is 128x128 (current logo is only 64 x 64).
- [ ] Correct documentation (with screenshots) for all actions and triggers.

### CODE REVIEW

**Comment by jhorbulyk** [comment]
@zubairov Here is what I have so far in making SugarCRM comply with our guidelines.  What should my next steps be.

**Comment by zubairov** [comment]
Very good work @jhorbulyk 

Are all triggers and actions provided by the component documented?

**Comment by zubairov** [comment]
Ah, sorry misunderstood the comment, documentation still need to be updated, right?

**Comment by zubairov** [comment]
BTW license file is already in the repository

**Pull request merged**
